### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#1264]
Inspect the pytest coverage report for all our public repos and identify missing unittests. We should probably exclude the api generated code from the coverage report.

Related #640 - only the core repo is currently connected to the Codecov website, we need to do the same for other repos.

**Comment by Adam-Boutin** [comment]
Hi Mainak, I am new to this but I would like to help out. I am trying to get a pytest coverage report from my fork but I am running into issues with the testing workflow. while running the tests on the GitHub CI I keep getting stuck on "waiting for a runner to pick up this job..." in the build documentation stage. I think it is this portion in the ci.yml 
 ``` 
docs_build:
     name: Build Documentation
     needs: [docs-style]
     runs-on: [self-hosted, pyfluent]
```
Any more information that you could give me would be a huge help. @mkundu1
